spring.datasource.url=${FINANCE_MANAGER_DB_URL}
spring.datasource.username=${FINANCE_MANAGER_DB_USERNAME}
spring.datasource.password=${FINANCE_MANAGER_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

server.forward-headers-strategy=framework
